Updating docker compose

diff --git a/docker/gecholog-ek-dev/docker-compose.yml b/docker/gecholog-ek-dev/docker-compose.yml
--- a/docker/gecholog-ek-dev/docker-compose.yml
+++ b/docker/gecholog-ek-dev/docker-compose.yml
@@ -9,7 +9,7 @@
 # Remove with volumes
 # docker-compose -f docker/gecholog-ek-dev/docker-compose.yml down -v
 
-# Requires export KIBANA_PASSWORD=<password>
+# Requires export PASSWORD=<password>
 
 version: "2.2"
 
@@ -21,13 +21,13 @@ services:
       - certs:/config/certs:z
       - configs:/app/conf:z
     environment:
-      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
+      - PASSWORD=${PASSWORD}
     user: "0"
-#            export KIBANA_PASSWORD=$KIBANA_PASSWORD;
+#            export PASSWORD=$PASSWORD;
     command: >
       sh -c '
-        if [ x${KIBANA_PASSWORD} == x ]; then
-          echo "Set the KIBANA_PASSWORD environment variable.";
+        if [ x${PASSWORD} == x ]; then
+          echo "Set the PASSWORD environment variable.";
           exit 1;
         fi;
         echo "By using gecholog you approve our license terms on docs.gecholog.ai. By using this software, you acknowledge and agree to the following terms and conditions: 1. This software is provided \"as is,\" without any warranties or guarantees, express or implied. You use it at your own risk. 2. The authors and contributors of this software shall not be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services, loss of use, data, or profits, or business interruption) arising in any way out of the use of this software. 3. You are expressly prohibited from: a. Reverse engineering, decompiling, disassembling, or attempting to discover the source code or algorithms of this software. b. Distributing, sublicensing, or making this software available to third parties without the prior written consent of the software owner. c. Copying, reproducing, or modifying this software or any part thereof, except as expressly permitted under applicable law. d. Engaging in any activity that infringes upon the intellectual property rights, copyrights, or trademarks associated with this software. 4. This is a licensed software to Artificial Solutions, and usage is conditioned on a valid license agreement with Artificial Solutions. 5. This software may include third-party libraries or components, each subject to its own licensing terms and conditions. Please review the licenses associated with these components for details. 6. You are solely responsible for complying with all applicable laws, regulations, and licensing agreements when using this software. 7. This disclaimer shall apply to the fullest extent permitted by law. If you do not agree to these terms or do not have a valid license agreement with Artificial Solutions, you should not use this software."
@@ -36,13 +36,13 @@ services:
         echo "Waiting for Elasticsearch availability";
         until curl -s --cacert config/certs/ca/ca.crt https://gl-elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done && echo "Step elastic [2/6]: PASSED" || (echo "Step elastic [2/6]: FAILED" && exit 1);
         echo "Setting kibana_system password";
-        until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:$KIBANA_PASSWORD -H "Content-Type: application/json" https://gl-elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"$KIBANA_PASSWORD\"}" | grep -q "^{}"; do sleep 10; done && echo "Step kibana pwd [3/6]: PASSED" || (echo "Step kibana pwd [3/6]: FAILED" && exit 1);
+        until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:$PASSWORD -H "Content-Type: application/json" https://gl-elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"$PASSWORD\"}" | grep -q "^{}"; do sleep 10; done && echo "Step kibana pwd [3/6]: PASSED" || (echo "Step kibana pwd [3/6]: FAILED" && exit 1);
         echo "Creating coburn1 index";
-        until curl -s -XPUT --cacert config/certs/ca/ca.crt -u elastic:$KIBANA_PASSWORD "https://gl-elasticsearch:9200/coburn1" -H "Content-Type: application/json" -d @elastic/index.json | grep -q "acknowledged\":true"; do sleep 10; done && echo "Step elastic index [4/6]: PASSED" || (echo "Step elastic index [4/6]: FAILED" && exit 1);
+        until curl -s -XPUT --cacert config/certs/ca/ca.crt -u elastic:$PASSWORD "https://gl-elasticsearch:9200/coburn1" -H "Content-Type: application/json" -d @elastic/index.json | grep -q "acknowledged\":true"; do sleep 10; done && echo "Step elastic index [4/6]: PASSED" || (echo "Step elastic index [4/6]: FAILED" && exit 1);
         echo "Waiting for Kibana availability"; 
         until curl -s --cacert config/certs/ca/ca.crt https://gl-kibana:5601/api/status | grep -q "available"; do sleep 30; done && echo "Step kibana up [5/6]: PASSED" || (echo "Step kibana up [5/6]: FAILED" && exit 1);
         echo "Populating dashboard";    
-        until curl -s --cacert config/certs/ca/ca.crt -u elastic:$KIBANA_PASSWORD -X POST "https://gl-kibana:5601/api/saved_objects/_import" -H "kbn-xsrf: true" -F file=@kibana/export.ndjson | grep -q "success\":true"; do sleep 10; done && echo "Step kibana dashboard [6/6]: PASSED" || (echo "Step kibana dashboard [6/6]: FAILED" && exit 1);
+        until curl -s --cacert config/certs/ca/ca.crt -u elastic:$PASSWORD -X POST "https://gl-kibana:5601/api/saved_objects/_import" -H "kbn-xsrf: true" -F file=@kibana/export.ndjson | grep -q "success\":true"; do sleep 10; done && echo "Step kibana dashboard [6/6]: PASSED" || (echo "Step kibana dashboard [6/6]: FAILED" && exit 1);
       '
     healthcheck:
       test: ["CMD-SHELL", "[ -f config/certs/elasticsearch/elasticsearch.crt ]"]
@@ -62,11 +62,10 @@ services:
     ports:
       - 5380:5380
       - 4222:4222
-      - 6222:6222
-      - 8222:8222
     environment:
       - AISERVICE_API_BASE=${AISERVICE_API_BASE}
-      - ELASTIC_PASSWORD=${KIBANA_PASSWORD}
+      - ELASTIC_PASSWORD=${PASSWORD}
+      - NATS_TOKEN=${PASSWORD}
       - NATS2LOG_LOGGER_SUBTOPIC=.logger
     healthcheck:
       test: ps | grep '/gl -o /app/conf/gl_config.json' | grep -v grep -q
@@ -80,6 +79,9 @@ services:
         condition: service_healthy
     image: gecholog/gl-nlp-spacy-entities:latest
     container_name: nlp-processor
+    environment:
+      - NATS_TOKEN=${PASSWORD}
+      - GECHOLOG_HOST=gecholog
     healthcheck:
       test: ps -x | grep 'python3 spacyentities.py' | grep -v grep -q
       interval: 1s
@@ -100,7 +102,7 @@ services:
     environment:
       - node.name=gl-elasticsearch
       - cluster.name=gecholog-ek-stack
-      - ELASTIC_PASSWORD=${KIBANA_PASSWORD}
+      - ELASTIC_PASSWORD=${PASSWORD}
       - bootstrap.memory_lock=true
       - discovery.type=single-node
       - xpack.security.enabled=true
@@ -147,7 +149,7 @@ services:
       - SERVER_NAME=gl-kibana
       - ELASTICSEARCH_HOSTS=https://gl-elasticsearch:9200
       - ELASTICSEARCH_USERNAME=kibana_system
-      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
+      - ELASTICSEARCH_PASSWORD=${PASSWORD}
       - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
       - SERVER_SSL_ENABLED=true
       - SERVER_SSL_CERTIFICATE=config/certs/kibana/kibana.crt
